(function(){
  "use strict";
  const $=id=>document.getElementById(id),history=[];
  let busy=false;
  const localGuides=[
    {keys:["باركود","منتج","صنف"],answer:"لإضافة منتج: افتح المنتجات والمخزون، اختر إضافة منتج، أدخل الاسم والسعر والكمية والباركود ثم احفظ. بعد ذلك يمكنك مسح الباركود من شاشة المبيعات لإضافة المنتج مباشرة إلى الفاتورة."},
    {keys:["طابعة","اطبع","طباعة","فاتورة"],answer:"افتح الإعدادات ثم قسم الطابعة ودرج الكاشير، اختر طريقة الاتصال ونفّذ طباعة تجريبية. عند تفعيل الطباعة التلقائية ستُحفظ عملية البيع أولاً ثم تُرسل الفاتورة للطابعة فوراً."},
    {keys:["ضريبة","vat","إقرار"],answer:"افتح صفحة الإقرار الضريبي، حدّد السنة والفترة وتاريخ البداية والنهاية، ثم حدّث التقرير. راجع المبيعات الخاضعة والضريبة الناتجة وضريبة المدخلات قبل الاعتماد، واستعن بمحاسب عند تقديم الإقرار الرسمي."},
    {keys:["صلاحية","صلاحيات","مستخدم","موظف"],answer:"افتح المستخدمون والصلاحيات، أضف المستخدم وحدد دوره، ثم فعّل فقط الأقسام التي يحتاجها. الأفضل إعطاء أقل صلاحية لازمة للعمل وعدم مشاركة حساب المالك."},
    {keys:["مخزون","كمية","تحويل"],answer:"من المنتجات والمخزون راجع الكمية، ومن تحويلات المخزون اختر فرع المصدر والفرع المستلم والأصناف. لا تعتبر الكمية مستلمة في الفرع الجديد حتى تأكيد الاستلام."},
    {keys:["مبيعات","كاشير","pos","دفع"],answer:"من شاشة المبيعات اختر الفرع والعميل وطريقة الدفع، أضف المنتجات بالضغط أو الباركود، راجع الإجمالي والضريبة ثم اضغط إتمام عملية البيع. في الدفع بالبطاقة سجّل الطريقة داخل VAREX بعد نجاح العملية على جهاز الدفع."},
    {keys:["أمان","اختراق","حماية","فيروس"],answer:"افتح مركز الأمان لإجراء فحص مباشر للاتصال والجلسة وعزل بيانات المنشأة. لا ترفع ملفات من مصادر مجهولة، وفعّل القفل التلقائي واستخدم كلمة مرور قوية وحساباً منفصلاً لكل مستخدم."}
  ];
  function now(){return new Date().toLocaleTimeString("ar-AE",{hour:"2-digit",minute:"2-digit"})}
  function append(role,message){const box=$("aiMessages");if(!box)return;const wrap=document.createElement("article");wrap.className=`ai-message ${role}`;const bubble=document.createElement("div");bubble.className="ai-bubble";bubble.textContent=message;const time=document.createElement("small");time.textContent=now();wrap.append(bubble,time);const thinking=$("aiThinking");if(thinking&&thinking.parentNode===box)box.insertBefore(wrap,thinking);else box.appendChild(wrap);box.scrollTop=box.scrollHeight;history.push({role:role==="user"?"user":"assistant",content:message});if(history.length>12)history.splice(0,history.length-12)}
  function localAnswer(message){const normalized=String(message||"").toLowerCase();const match=localGuides.find(guide=>guide.keys.some(key=>normalized.includes(key)));return match?.answer||"أقدر أساعدك في المبيعات، المنتجات، المخزون، الطباعة، الضريبة، المستخدمين والأمان. اكتب اسم القسم أو صف المشكلة بالتفصيل لأعطيك الخطوات المناسبة."}
  async function remoteAnswer(message){const session=window.VAREX?.getSession?.();if(!session?.access_token)throw new Error("AUTH_REQUIRED");const response=await fetch(`${window.VAREX.config.supabaseUrl}/functions/v1/varex-ai-assistant`,{method:"POST",headers:{apikey:window.VAREX.config.supabaseKey,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({message,history:history.slice(0,-1).slice(-6)})});let data={};try{data=await response.json()}catch(error){}if(!response.ok||!data?.answer)throw new Error(data?.code||"AI_UNAVAILABLE");return String(data.answer)}
  function setBusy(next){busy=next;const button=$("aiSend"),thinking=$("aiThinking");if(button)button.disabled=next;if(thinking)thinking.classList.toggle("show",next)}
  async function send(raw){const message=String(raw||"").trim().slice(0,1200);if(!message||busy)return;append("user",message);$("aiInput").value="";updateCounter();setBusy(true);try{const answer=await remoteAnswer(message);text("aiMode","مساعد VAREX الذكي");append("assistant",answer)}catch(error){text("aiMode","الوضع الإرشادي المحلي");append("assistant",localAnswer(message))}finally{setBusy(false);$("aiInput")?.focus()}}
  function text(id,value){const node=$(id);if(node)node.textContent=value}
  function updateCounter(){const input=$("aiInput");text("aiCounter",`${input?.value.length||0} / 1200`)}
  function clock(){const date=new Date();text("currentDate",date.toLocaleDateString("ar-AE",{timeZone:"Asia/Dubai",year:"numeric",month:"2-digit",day:"2-digit"}));text("currentTime",date.toLocaleTimeString("ar-AE",{timeZone:"Asia/Dubai",hour:"2-digit",minute:"2-digit",second:"2-digit"}))}
  document.addEventListener("DOMContentLoaded",()=>{const form=$("aiForm"),input=$("aiInput"),messages=$("aiMessages");const thinking=document.createElement("div");thinking.id="aiThinking";thinking.className="ai-thinking";thinking.innerHTML="<span>جاري إعداد الإجابة</span><i></i><i></i><i></i>";messages?.appendChild(thinking);append("assistant","مرحباً، أنا مساعد VAREX. كيف أقدر أساعدك اليوم في تشغيل النظام؟");form?.addEventListener("submit",event=>{event.preventDefault();send(input?.value)});input?.addEventListener("input",updateCounter);input?.addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();send(input.value)}});document.querySelectorAll(".ai-prompt").forEach(button=>button.addEventListener("click",()=>send(button.textContent)));let user={};try{user=window.VAREX?.getCurrentUser?.()||{}}catch(error){}text("topUserName",user.name||user.username||user.email||"المستخدم");clock();setInterval(clock,1000);updateCounter()});
})();
