"use client";
import {useEffect,useState} from "react";
const languages=[["ar","العربية","rtl"],["en","English","ltr"],["fr","Français","ltr"],["ur","اردو","rtl"],["it","Italiano","ltr"],["es","Español","ltr"],["fa","فارسی","rtl"],["ru","Русский","ltr"],["zh","中文","ltr"],["ku","Kurdî","rtl"],["de","Deutsch","ltr"],["pt","Português","ltr"],["tr","Türkçe","ltr"],["hi","हिन्दी","ltr"],["bn","বাংলা","ltr"],["ja","日本語","ltr"],["ko","한국어","ltr"],["id","Indonesia","ltr"],["ms","Melayu","ltr"],["he","עברית","rtl"]];
const tools=[["⌂","مركز القيادة"],["▰","المشاريع"],["⌁","الموقع اليومي"],["▤","المخططات"],["◷","البرنامج الزمني"],["د.إ","التكاليف"],["⇄","التغييرات"],["⚑","الجودة والسلامة"],["⚙","المعدات"],["◎","التقارير"]];
const phases=[["أعمال الهيكل","اليوم","82%","live"],["الأعمال الكهروميكانيكية","28 أغسطس","61%",""],["الواجهات الخارجية","12 سبتمبر","35%",""],["التشطيبات","3 أكتوبر","12%",""]];
const projects=[["برج المارينا","دبي","74%","ضمن الخطة"],["فلل الياسمين","الشارقة","51%","ضمن الخطة"],["مستودعات جبل علي","دبي","28%","متأخر 4 أيام"]];
export default function Home(){const[active,setActive]=useState("مركز القيادة"),[lang,setLang]=useState("ar"),[langOpen,setLangOpen]=useState(false),[panel,setPanel]=useState(false),[modal,setModal]=useState(false);const li=languages.find(x=>x[0]===lang)||languages[0];useEffect(()=>{document.documentElement.dir=li[2];document.documentElement.lang=lang},[lang,li]);return <main className="app" dir={li[2]}>
<header className="top"><button className="hamb" onClick={()=>setPanel(!panel)}>☰</button><div className="logo"><img src="/varex-construction-logo.png" alt="VAREX Business Management App"/><div><b>VAREX</b><small>BUSINESS MANAGEMENT APP</small></div></div><div className="projectSwitch"><span>المشروع الحالي</span><b>برج المارينا السكني</b><i>⌄</i></div><div className="topActions"><button className="status"><i/>النظام متصل</button><div className="language"><button onClick={()=>setLangOpen(!langOpen)}>🌐 {li[1]}⌄</button>{langOpen&&<div className="langMenu">{languages.map(x=><button key={x[0]} onClick={()=>{setLang(x[0]);setLangOpen(false)}} className={lang===x[0]?"on":""}>{x[1]}<b>{lang===x[0]?"✓":""}</b></button>)}</div>}</div><button>☼</button><button>♢<em>3</em></button><div className="profile"><span>م ع</span><b>محمد العلي<small>مدير المشاريع</small></b></div></div></header>
<div className="body"><aside className={panel?"dock open":"dock"}><div className="dockLabel">مساحات العمل</div>{tools.map(([i,t])=><button key={t} className={active===t?"active":""} onClick={()=>{setActive(t);setPanel(false)}}><i>{i}</i><span>{t}</span></button>)}<div className="dockBottom"><button><i>♙</i><span>تبديل المستخدم</span></button><button className="logout"><i>↪</i><span>تسجيل الخروج</span></button></div></aside>
<section className="canvas">{active!=="مركز القيادة"?<Module title={active}/>:<><div className="hero"><div><span className="crumb">مركز عمليات المقاولات / اليوم</span><h1>الموقع تحت السيطرة.</h1><p>متابعة مباشرة للتنفيذ، الموارد، التكلفة والمخاطر من شاشة واحدة.</p></div><div className="heroActions"><button className="ghost">تنزيل التقرير</button><button className="mainBtn" onClick={()=>setModal(true)}>＋ إنشاء مشروع</button></div></div>
<div className="metricStrip"><Metric n="12" t="مشروعاً نشطاً" d="3 قرب التسليم" c="mint"/><Metric n="64.8 م" t="قيمة العقود" d="+8.2% هذا الشهر" c="blue"/><Metric n="68%" t="الإنجاز العام" d="وفق البرنامج" c="violet"/><Metric n="7" t="قرارات معلّقة" d="2 عاجلة اليوم" c="orange"/></div>
<div className="commandGrid"><article className="siteCard"><div className="cardTop"><div><span className="sectionNo">01</span><h2>نبض الموقع</h2><p>برج المارينا • آخر تحديث قبل 8 دقائق</p></div><button>فتح يومية الموقع ←</button></div><div className="siteVisual"><div className="floor f1"><b>12</b><span>قيد الصب</span></div><div className="floor f2"><b>11</b><span>مكتمل</span></div><div className="floor f3"><b>10</b><span>مكتمل</span></div><div className="towerBase"/></div><div className="siteStats"><span><b>184</b>عامل بالموقع</span><span><b>9</b>معدات تعمل</span><span><b>0</b>حادث اليوم</span></div></article>
<article className="timelineCard"><div className="cardTop"><div><span className="sectionNo">02</span><h2>خط التنفيذ</h2><p>المراحل الحرجة للمشروع</p></div><button>البرنامج الكامل ←</button></div><div className="phases">{phases.map(([n,d,p,c])=><div className={c} key={n}><i/><section><b>{n}</b><small>{d}</small></section><strong>{p}</strong><span><em style={{width:p}}/></span></div>)}</div><div className="deadline"><span>موعد التسليم المتوقع</span><b>18 ديسمبر 2026</b><small>متقدم 6 أيام عن الخطة</small></div></article></div>
<div className="lowerGrid"><article className="costCard"><div className="cardTop"><div><span className="sectionNo">03</span><h2>مؤشر التكلفة</h2><p>الميزانية مقابل المصروف الفعلي</p></div><button>آخر 6 أشهر⌄</button></div><div className="costNumbers"><span><small>الميزانية المعتمدة</small><b>18.40 م</b></span><span><small>المصروف حتى اليوم</small><b>12.16 م</b></span><span><small>التوقع عند الإغلاق</small><b>17.62 م</b></span></div><div className="costTrack"><i style={{width:"66%"}}/><em style={{left:"74%"}}/></div><div className="costLegend"><span>66% مصروف</span><b>وفر متوقع 780,000 د.إ</b></div></article>
<article className="riskCard"><div className="cardTop"><div><span className="sectionNo">04</span><h2>غرفة القرارات</h2><p>ما يحتاج موافقتك اليوم</p></div><button>عرض الكل</button></div><Decision c="red" t="تأخر توريد حديد التسليح" m="تأثير محتمل: 4 أيام" a="معالجة الآن"/><Decision c="amber" t="أمر تغيير الواجهة الشرقية" m="القيمة: 126,000 د.إ" a="اعتماد"/><Decision c="green" t="فحص عزل الطابق التاسع" m="اجتاز فحص الجودة" a="عرض"/></article></div>
<article className="portfolio"><div className="cardTop"><div><span className="sectionNo">05</span><h2>محفظة المشاريع</h2><p>مقارنة سريعة للمشاريع النشطة</p></div><button>إدارة المشاريع ←</button></div><div className="projectRows">{projects.map((p,i)=><div key={p[0]}><span className="code">0{i+1}</span><b>{p[0]}<small>{p[1]}</small></b><span className="pbar"><i style={{width:p[2]}}/></span><strong>{p[2]}</strong><mark className={i===2?"late":""}>{p[3]}</mark><button>←</button></div>)}</div></article></>}</section></div>
{panel&&<div className="shade" onClick={()=>setPanel(false)}/>}
{modal&&<div className="modal"><form onSubmit={e=>{e.preventDefault();setModal(false)}}><button type="button" className="x" onClick={()=>setModal(false)}>×</button><span className="sectionNo">مشروع جديد</span><h2>إنشاء مشروع مقاولات</h2><label>اسم المشروع<input required placeholder="مثال: برج الخليج السكني"/></label><div><label>المدينة<input required placeholder="دبي"/></label><label>قيمة العقد<input placeholder="0.00 د.إ"/></label></div><div><label>تاريخ البدء<input type="date"/></label><label>تاريخ التسليم<input type="date"/></label></div><footer><button type="button" onClick={()=>setModal(false)}>إلغاء</button><button className="mainBtn">حفظ المشروع</button></footer></form></div>}</main>}
function Metric({n,t,d,c}:{n:string,t:string,d:string,c:string}){return <div className={"metric "+c}><i/><strong>{n}</strong><span>{t}<small>{d}</small></span></div>}
function Decision({c,t,m,a}:{c:string,t:string,m:string,a:string}){return <div className="decision"><i className={c}/><b>{t}<small>{m}</small></b><button>{a}</button></div>}
function Module({title}:{title:string}){return <div className="module"><span className="sectionNo">VAREX CONSTRUCTION</span><h1>{title}</h1><p>وحدة مستقلة لإدارة السجلات والعمليات الخاصة بـ {title}.</p><div className="moduleGrid"><button>＋ إضافة سجل جديد</button><button>⌕ بحث وتصفية</button><button>⇩ تصدير التقرير</button></div></div>}
